name: Build Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install libpcap
        run: sudo apt-get install libpcap-dev

      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: add to PATH
        run: echo $(go env GOPATH)/bin >> $GITHUB_PATH

      - name: check fmt
        run: make check-fmt

      - name: check go.mod
        shell: bash
        run: |
          go mod tidy
          git diff-index --quiet HEAD

      - name: go test
        run: go test ./...

      - name: go build
        run: go build

      - name: build image
        run: make docker
